# Model architectures
from .self_supervised_learning import MaskedAutoEncoder, ContrastiveLearning
from .fusion import MultiModalFusionNetwork, ExplainableFusionNetwork
from .foundation_models import FoundationModelManager